# Sửa lại thành đường dẫn này để Render có quyền ghi file
spring.datasource.url=jdbc:sqlite:data.db
# đường dẫn trên là file Chinook của DBeaver, bạn có thể thay bằng đường dẫn khác nếu muốn, nhưng nhớ là phải có quyền ghi file để Hibernate có thể tạo bảng và lưu dữ liệu
#spring.datasource.url=jdbc:sqlite:data.db # Đường dẫn này sẽ tạo file data.db trong thư mục gốc của dự án nếu chưa có
spring.datasource.driver-class-name=org.sqlite.JDBC
# Thêm dòng này để Hibernate tự tạo bảng nếu chưa có
spring.jpa.hibernate.ddl-auto=update



# 2. Cấu hình để Hibernate (Spring JPA) hoạt động với SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update



server.port=${PORT:8080}
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
